module geometry_msgs {
  module msg {
    @verbatim (language="comment", text=" This represents a vector in free space.")
    struct Vector3 {
      double x;

      double y;

      double z;
    };
  };
};
